"""Initial Migration

Revision ID: 1b2d16dd3498
Revises: 3983a745bf84
Create Date: 2019-09-24 10:36:54.828071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b2d16dd3498'
down_revision = '3983a745bf84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('post', sa.Text(), nullable=True))
    op.add_column('categories', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('categories', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'])
    op.drop_column('categories', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'user_id')
    op.drop_column('categories', 'title')
    op.drop_column('categories', 'post')
    # ### end Alembic commands ###
